apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-analyser-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutrition-analyser-container
  template:
    metadata:
      labels:
        app: nutrition-analyser-container
    spec:
      containers:
        - name: nutrition-analyser-container
          image: 'IMAGE_TAG_BACKEND_CONTAINER'
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080