apiVersion: v1
kind: Service
metadata:
  name: nutrition-analyser-container-service
spec:
  selector:
    app: nutrition-analyser-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  